version: '3.8'

services:
  db:
    image: postgres:15
    container_name: koi_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=koi_user
      - POSTGRES_PASSWORD=koi_password
      - POSTGRES_DB=koi_market_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: